apiVersion: 1

datasources:
  - name: PostgreSQL-Reperibilita
    uid: oncall-postgres
    type: postgres
    url: postgres:5432
    database: reperibilita
    user: ${GF_POSTGRES_USER}
    secureJsonData:
      password: ${GF_POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
